import { Client, Events, GatewayIntentBits, messageLink } from "discord.js";
import { GoogleGenAI } from "@google/genai";

import dotenv from "dotenv";

dotenv.config();

const client = new Client({
     intents: [
          GatewayIntentBits.Guilds,
          GatewayIntentBits.GuildMessages,
          GatewayIntentBits.GuildExpressions,
          GatewayIntentBits.GuildMessagePolls,
          GatewayIntentBits.GuildMessageTyping,
          GatewayIntentBits.GuildMessageReactions,
          GatewayIntentBits.DirectMessages,
          GatewayIntentBits.DirectMessageTyping,
          GatewayIntentBits.DirectMessageReactions,
          GatewayIntentBits.DirectMessagePolls,
          GatewayIntentBits.MessageContent,
     ]
});
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY  });

const main_AI_function = async (userQuery) => {
     try {
          const response = await ai.models.generateContent({
               model: "gemini-2.5-flash",
               contents: `${userQuery} in 5 lines`,
          });

          return response.text;
     } catch (error) {
          console.log(error);

          return "error-occured-during-ai-response";
     }
}

client.on("messageCreate", async (message) => {
     if (message.author.bot) return;
     
     if (message.content.startsWith('gemini-mode: ')) {
          const result = await main_AI_function(message.content.split('gemini-mode: ')[1]);

          message.reply({
               content: `
               -----------------------------------CONTENT GENERATED BY AI ----------------------------\n${result}
               `,
          });
          
          return;
     }

     message.reply({
          content: `Hello ${message.author.username}, I hope you are doing well :)`,
     })
});

client.on("interactionCreate", interaction => {
     if (interaction.user.bot) return;

     interaction.reply("Pong!");
})

client.login(process.env.DISCORD_BOT_TOKEN);